server:
  port: 6631

spring:
  application:
    name: kingcent-campus-auth
  datasource:
    username: root
    password: 11223344aaa
    url: jdbc:mysql://localhost:3306/kingcent_campus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000
  data:
    redis:
      timeout: 300s
      host: localhost
      port: 6379
      database: 0
#      password: qcxyg666
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 500
          min-idle: 0

  cloud:
    nacos:
      discovery:
#        server-addr: 175.178.107.254:8848
#        username: nacos
        server-addr: localhost:8848
#        password: nacos


mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto