server:
  port: 6635

spring:
  application:
    name: kingcent-campus-community
  jackson:
    default-property-inclusion: non_null #为空的json字段不返回
  data:
    redis:
      timeout: 300s
      host: localhost
      port: 6379
      database: 0
      #      password: qcxyg666
      jedis:
        pool:
          max-active: 8
          max-wait: -1ms
          max-idle: 500
          min-idle: 0

  datasource:
    username: root
    password: 11223344aaa
    url: jdbc:mysql://localhost:3306/kingcent_campus?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    #    username: kc
    #    password: 38d58FdcsjHKsS7N
    #    url: jdbc:mysql://175.178.186.82:3306/kc?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&allowPublicKeyRetrieval=true&zeroDateTimeBehavior=convertToNull
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      max-lifetime: 120000

  cloud:
    nacos:
      discovery:
        #        server-addr: 175.178.186.82:8848
        #        username: nacos
        #        password: nacos
        server-addr: localhost:8848

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDeleted
      logic-delete-value: 1
      logic-not-delete-value: 0
      id-type: auto